### ISSUE TITLE
Change PK/FK for Pass Holder and Parking Pass

### ISSUE THREAD

**Issue by itstonywu** [sassansh/Parking-Lot-Database#23]
Should we be keeping the customer in the database if we delete a pass holder? Currently if we delete a pass holder, the parking pass still exists in the database. 

![image](https://user-images.githubusercontent.com/22286446/84585438-ad3ef100-adc4-11ea-9293-224ae75df84c.png)

**Comment by itstonywu** [comment]
Customer 123 was removed from pass holder but the parking pass was not

**Comment by sassansh** [comment]
yeah that's definitely not what we want. When a customer is deleted we should either delete their pass too OR not allow a customer to be deleted until all their passes are. 

I think: when a customer is asking to be removed, we should just remove all their passes and slips. But if they have fines.. then we shouldn't allow them to be removed.

**Comment by itstonywu** [comment]
@sassansh okay, I can just remove the customer key when I select a row instead. I had that before but just wanted to check whether that was the intent or if we can delete a pass holder without deleting the pass holder.
