### ISSUE TITLE
Add more rows to the rate table

### ISSUE THREAD

**Issue by itstonywu** [sassansh/Parking-Lot-Database#36]

**Comment by itstonywu** [comment]
@sassansh or @Junkim97 can you please take care of this for me? 

In the rate table, can you add all the rate types for all the lots? 

ie.  each lot has all rate types 

Need to add some data so it we have more than 1 row populating the table in my projection query

Thanks!

**Comment by itstonywu** [comment]
Sorry mad busy with work today and it is quick fix

**Comment by sassansh** [comment]
@tonywu94 yep! Ill take care of this.
