### ISSUE TITLE
InsertParkingSpace & SelectParkingSpace doesn't show all possible parking space types

### ISSUE THREAD

**Issue by sassansh** [sassansh/Parking-Lot-Database#39]
Here is what it shows:
![image](https://user-images.githubusercontent.com/40008576/84726127-059afd80-af41-11ea-880d-4c30cf35cee8.png)

Here are the space types that are in the database:
![image](https://user-images.githubusercontent.com/40008576/84726160-1b102780-af41-11ea-9b51-1320298f35d6.png)

**Comment by sassansh** [comment]
even for the Select Parking Space page, you could show all possible types then say or show nothing found. you currently look at parking spaces to get the types, so it only shows the space types that are currently in use, you should look at our rates type
![image](https://user-images.githubusercontent.com/40008576/84726400-9f62aa80-af41-11ea-9994-70c17595a08c.png)

**Comment by Junkim97** [comment]
That's because the parking space table hasn't been populated with any spots of of those types.

**Comment by sassansh** [comment]
but you should be able to add a space of that type given that it exists in the rates table, no? The lot doesnt currently have any medium size spaces but given that it exists in the rates table, you should be able to add a space of that type.

**Comment by sassansh** [comment]
Parking Spaces' space_type references Rates:
`    FOREIGN KEY (Space_Type) References Rate(Rate_Type)`

**Comment by Junkim97** [comment]
![MileStone 2](https://user-images.githubusercontent.com/53490816/84726913-c53c7f00-af42-11ea-9ba0-323b4e999a9b.png)
![MileStone3](https://user-images.githubusercontent.com/53490816/84727183-5875b480-af43-11ea-9edb-8033d7e4b979.png)


Um looking back at our submissions for the milestones Space_Type is not a FK when did we change that?

**Comment by sassansh** [comment]
In the normalization, we incorrectly created a M:M table for a space and a rate. However a space can only have one rate. So it is correctly stored in the space now. Was a recent change. There’s a commit for it.

**Comment by Junkim97** [comment]
Ok I'll take a look tomorrow.

**Comment by sassansh** [comment]
fixed it!
